### ISSUE TITLE
请问MDG的实现部分在哪？get_method_vec.py中这个注释掉了# def get_openne_dict():

### ISSUE THREAD

**Issue by QuanixnYang** [wangsiqidahaoren/Rmove-method#1]
`# def get_openne_dict():
#     file = open(_openne_file, 'r', encoding='utf-8')
#     lines = file.readlines()
#     for line in lines:
#         p1 = re.compile(r'[(](.*?)[)]', re.S)  # 最小匹配
#         method_name = re.findall(p1, line)[0]  # 获取每个方向向量的信息（类名+方法名）
#         vec = line.strip().rstrip(']').replace(' ', '').split(',')
#         del vec[0]
#         _openne_dict[method_name] = vec
#     file.close()`

您好，我想请教下，get_method_vec.py中上面这部分代码注释了，是没有使用论文中说的MDG的信息吗？

**Comment by yongguoguo** [comment]
我们对MDG的向量表征获取集成到concat_vec()方法中
`file = open(_openne_file, 'r', encoding='utf-8')
    lines = file.readlines()`
这里代替了get_method_vec.py方法，获取MDG表征向量

**Comment by QuanixnYang** [comment]
> 我们对MDG的向量表征获取集成到concat_vec()方法中 `file = open(_openne_file, 'r', encoding='utf-8') lines = file.readlines()` 这里代替了get_method_vec.py方法，获取MDG表征向量

感谢您的回复，想进一步请教下MDG结构信息是怎么提取的，有没有对应的代码，没找到生成_openne_file的相关代码，感谢！！

**Comment by QuanixnYang** [comment]
> > 我们对MDG的向量表征获取集成到concat_vec()方法中 `file = open(_openne_file, 'r', encoding='utf-8') lines = file.readlines()` 这里代替了get_method_vec.py方法，获取MDG表征向量
> 
> 感谢您的回复，想进一步请教下MDG结构信息是怎么提取的，有没有对应的代码，没找到生成_openne_file的相关代码，感谢！！
o,找到了
